name 'setup'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'morgan@jmorgan.org'
license 'MIT'
description 'Initial setup for machines in JML Organization'
version '0.5.2'

depends 'chef-vault', '~> 1.3'
depends 'apt', '~> 2.8'
depends 'chef-client', '~> 4.3'
depends 'yum-epel', '~> 0.6'
depends 'ntp', '~> 1.8'
depends 'firewalld', '~> 1.1'
